# Generated by Django 4.1.dev20211115193433 on 2021-11-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lar',
            old_name='user',
            new_name='owner',
        ),
    ]
