# Generated by Django 4.1.dev20211115193433 on 2021-11-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_user_lar_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='visit_date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
