# Generated by Django 4.1.dev20211115193433 on 2021-11-22 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_alter_visita_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipa',
            name='team_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
