# Generated by Django 4.1.dev20211115193433 on 2021-11-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_equipa_team_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lar',
            old_name='lar_user',
            new_name='users',
        ),
    ]
