# Generated by Django 4.1.dev20211115193433 on 2021-11-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_rename_lar_user_lar_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
