# Generated by Django 4.1.dev20211115193433 on 2021-11-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_produto_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='lar_list',
            new_name='lar',
        ),
    ]
