# Generated by Django 3.2.9 on 2021-11-30 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_rename_lar_list_visita_lar'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='infected_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infected_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('used_product', models.ManyToManyField(to='polls.Produto')),
                ('visited_lar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.lar')),
            ],
        ),
    ]
