# Generated by Django 3.2.9 on 2021-11-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20211130_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipa',
            old_name='team_user',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Intervention',
        ),
    ]
