# Generated by Django 3.2.9 on 2021-11-30 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0011_auto_20211130_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='infected_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
